### ISSUE TITLE
Support different update strategy in manifestwork

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/work#123]
Currently, the work agent sends an update call for any manifests in the manifestwork if it is changed in manifestwork or modified on the spoke, though have some special treatment on some known resources like Secret/Configmap.

It may cause some resource dangling if this resource is also controlled by another actor on the spoke. For example, this actor may update the spec of the resource for other purposes. We should consider allowing user to define an update strategy in manifestwork to tolerate other actors.

/kind feature

**Comment by qiujian16** [comment]
cc @yue9944882 

/assign @qiujian16

**Comment by yue9944882** [comment]
thanks for kicking this off. the point of generalizing an update strategy is enabling the work agent to update merely a subset of the consisting objects to the managed cluster, with that being said, the rest portion of the object should not be updated until other actors explicitly "claim"s those fields. then multiple writers can manipulate the same object w/o conflicts in parallel. this is exactly what the kubernetes feature [SSA/"server-side-apply"](https://kubernetes.io/docs/reference/using-api/server-side-apply/) trying to accomplish, by modelling SSA as an update strategy in the work api will help us significantly simplify how to coordinate the writes from external controllers. e.g. a deployment resource in the spoke cluster can be majorly managed by the work agent while its ".spec.replicas" path can be exclusively managed by an autoscaler. 

however SSA was fresh graduated into GA since 1.22 (beta since 1.16, but idk if all the fixes before 1.22 are consistently picked to older releases b/c the maintain windowns in kubernetes only 3 releases), so i suppose we still need a solution for non-SSA spoke clusters. regarding that AFAIK there're two outstanding concerns in generalizing a update strategy in the work api:

- __managing the field deletion__: say we had an object "A" in a work. then the next moment, we removed ".spec.foo" from that "A". what is the expected behavior for the work agent then? e.g. is ".spec.foo" supposed to be vanished from the local "A" or is the field orphaned/relaxed remaining the previous value. 

- __correctly dealing w/ 3-way merge__: in the current implementation of work agent we're using `resourceapply.ApplyDirect(..)` for updating those builtin types, the method hardcoded how to do the merging at the client-side and use the "resource-version" to assert no 3rd update are cutting in the mid otherwise it returns a conflict.  __however__ for the custom resources we're just [copy/pasting the latest resource-version to the template data](https://github.com/open-cluster-management-io/work/blob/main/pkg/spoke/controllers/manifestcontroller/manifestwork_controller.go#L334), so any local non-status writes upon cr will be reset back by the work agent (except the owner-ref). in a correct 3-way merge, we should make sure the final state of the object is computed from (1) last observed state (2) expected state (3) actual state of the object.
